ci: trying to debug check_bump error on github workflows

diff --git a/.github/actions/check-bump/action.yml b/.github/actions/check-bump/action.yml
--- a/.github/actions/check-bump/action.yml
+++ b/.github/actions/check-bump/action.yml
@@ -21,15 +21,23 @@ runs:
     id: check_bump
     shell: bash
     run: |
-      bump_output=$(cz bump --yes --dry-run)
+      echo "Running cz bump --yes --dry-run"
+      bump_output=$(cz bump --yes --dry-run 2>&1)
+      echo "Bump output:"
+      echo "$bump_output"
       printf "%s\n" "$bump_output" >> bump-output.txt
-      if [ $? -eq 0 ]; then
+      if echo "$bump_output" | grep -q '[NO_COMMITS_TO_BUMP]'; then
+        echo "No commits to bump"
+        echo "bump_needed=false" >> $GITHUB_OUTPUT
+      elif [ $? -eq 0 ]; then
+        echo "Bump needed"
         echo "bump_needed=true" >> $GITHUB_OUTPUT
         from_version=$(echo "$bump_output" | grep -oP 'version [0-9]+\.[0-9]+\.[0-9]+ → [0-9]+\.[0-9]+\.[0-9]+' | cut -d' ' -f2)
         to_version=$(echo "$bump_output" | grep -oP 'version [0-9]+\.[0-9]+\.[0-9]+ → [0-9]+\.[0-9]+\.[0-9]+' | cut -d' ' -f4)
         echo "from_version=$from_version" >> $GITHUB_OUTPUT
         echo "to_version=$to_version" >> $GITHUB_OUTPUT
       else
+        echo "Error running cz bump"
         echo "bump_needed=false" >> $GITHUB_OUTPUT
       fi
   
